---
- name: Converge
  hosts: all
  become: yes
  vars:
    docker_port: "{{ molecule_yml.provisioner.vars.docker_port }}"
  tasks:
    - name: "Include docker_secured"
      include_role:
        name: "docker_secured"
