---
# tasks file for docker_secured
- name: install firewalld
  package:
     name: firewalld

- name: deploy ssl configuration
  include: ssl.yml

- name: expose secure docker API
  include: secure.yml
