---
- name: deploy docker secured config
  template:
    dest: /etc/systemd/system/docker.service.d/override.conf
    src: templates/secured.override.conf.j2
  notify:
    - reload units
    - restart docker

- name: expose port {{ docker_port }}
  firewalld:
    port: "{{ docker_port }}/tcp"
    permanent: yes
    state: enabled
