---
# handlers file for docker_secured
#
# reload units when configuration got changed
- name: reload units
  systemd:
    daemon_reload: yes
#
# restart docker when configuration got changed
- name: restart docker
  service:
    name: docker
    state: restarted
